class Autogenerated {
  List<ResourcesModel>? resources;

  Autogenerated({this.resources});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['resources'] != null) {
      resources = <ResourcesModel>[];
      json['resources'].forEach((v) {
        resources!.add(new ResourcesModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.resources != null) {
      data['resources'] = this.resources!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ResourcesModel {
  int? id;
  String? name;
  String? code;
  String? designation;
  String? email;
  String? mobileCode;
  String? mobileNo;

  ResourcesModel(
      {this.id,
        this.name,
        this.code,
        this.designation,
        this.email,
        this.mobileCode,
        this.mobileNo});

  ResourcesModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    code = json['code'];
    designation = json['designation'];
    email = json['email'];
    mobileCode = json['mobileCode'];
    mobileNo = json['mobileNo'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['code'] = this.code;
    data['designation'] = this.designation;
    data['email'] = this.email;
    data['mobileCode'] = this.mobileCode;
    data['mobileNo'] = this.mobileNo;
    return data;
  }
}