class AutogeneratedResponse{
  List<ProjectsModel>? projects;

  AutogeneratedResponse({this.projects});

  AutogeneratedResponse.fromJson(Map<String, dynamic> json) {
    if (json['projects'] != null) {
      projects = <ProjectsModel>[];
      json['projects'].forEach((v) {
        projects!.add(new ProjectsModel.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.projects != null) {
      data['projects'] = this.projects!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ProjectsModel {
  int? id;
  String? name;
  String? code;

  ProjectsModel({this.id, this.name, this.code});

  ProjectsModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    code = json['code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['code'] = this.code;
    return data;
  }
}