// class Autogenerated {
//   Configuration? configuration;
//   TaskLogInfo? taskLogInfo;
//
//   Autogenerated({this.configuration, this.taskLogInfo});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     configuration = json['configuration'] != null
//         ? new Configuration.fromJson(json['configuration'])
//         : null;
//     taskLogInfo = json['taskLogInfo'] != null
//         ? new TaskLogInfo.fromJson(json['taskLogInfo'])
//         : null;
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.configuration != null) {
//       data['configuration'] = this.configuration!.toJson();
//     }
//     if (this.taskLogInfo != null) {
//       data['taskLogInfo'] = this.taskLogInfo!.toJson();
//     }
//     return data;
//   }
// }
//
// class Configuration {
//   List<Accounts>? accounts;
//   List<Projects>? projects;
//   List<Buildings>? buildings;
//   List<TaskStatuses>? taskStatuses;
//   List<TaskInstructions>? taskInstructions;
//   List<Types>? types;
//   List<SubTypes>? subTypes;
//   List<Categories>? categories;
//   List<Channels>? channels;
//   List<Locs>? locs;
//   List<Priorities>? priorities;
//   List<FaultCodes>? faultCodes;
//   List<SubTaskTypes>? subTaskTypes;
//   List<SubTaskStatuses>? subTaskStatuses;
//   List<OnHoldReasons>? onHoldReasons;
//   List<Countries>? countries;
//   List<ReporterTypes>? reporterTypes;
//   List<ReporterSubTypes>? reporterSubTypes;
//
//
//
//
//   Configuration(
//       {this.accounts,
//         this.projects,
//         this.buildings,
//         this.taskStatuses,
//         this.taskInstructions,
//         this.types,
//         this.subTypes,
//         this.categories,
//         this.channels,
//         this.locs,
//         this.priorities,
//         this.faultCodes,
//         this.subTaskTypes,
//         this.subTaskStatuses,
//         this.onHoldReasons,
//         this.countries,
//         this.reporterTypes,
//         this.reporterSubTypes});
//
//   Configuration.fromJson(Map<String, dynamic> json) {
//     if (json['accounts'] != null) {
//       accounts = <Accounts>[];
//       json['accounts'].forEach((v) {
//         accounts!.add(new Accounts.fromJson(v));
//       });
//     }
//     if (json['projects'] != null) {
//       projects = <Projects>[];
//       json['projects'].forEach((v) {
//         projects!.add(new Projects.fromJson(v));
//       });
//     }
//     if (json['buildings'] != null) {
//       buildings = <Buildings>[];
//       json['buildings'].forEach((v) {
//         buildings!.add(new Buildings.fromJson(v));
//       });
//     }
//     if (json['taskStatuses'] != null) {
//       taskStatuses = <TaskStatuses>[];
//       json['taskStatuses'].forEach((v) {
//         taskStatuses!.add(new TaskStatuses.fromJson(v));
//       });
//     }
//     if (json['taskInstructions'] != null) {
//       taskInstructions = <TaskInstructions>[];
//       json['taskInstructions'].forEach((v) {
//         taskInstructions!.add(new TaskInstructions.fromJson(v));
//       });
//     }
//     if (json['types'] != null) {
//       types = <Types>[];
//       json['types'].forEach((v) {
//         types!.add(new Types.fromJson(v));
//       });
//     }
//     if (json['subTypes'] != null) {
//       subTypes = <SubTypes>[];
//       json['subTypes'].forEach((v) {
//         subTypes!.add(new SubTypes.fromJson(v));
//       });
//     }
//     if (json['categories'] != null) {
//       categories = <Categories>[];
//       json['categories'].forEach((v) {
//         categories!.add(new Categories.fromJson(v));
//       });
//     }
//     if (json['channels'] != null) {
//       channels = <Channels>[];
//       json['channels'].forEach((v) {
//         channels!.add(new Channels.fromJson(v));
//       });
//     }
//     if (json['locs'] != null) {
//       locs = <Locs>[];
//       json['locs'].forEach((v) {
//         locs!.add(new Locs.fromJson(v));
//       });
//     }
//     if (json['priorities'] != null) {
//       priorities = <Priorities>[];
//       json['priorities'].forEach((v) {
//         priorities!.add(new Priorities.fromJson(v));
//       });
//     }
//     if (json['faultCodes'] != null) {
//       faultCodes = <FaultCodes>[];
//       json['faultCodes'].forEach((v) {
//         faultCodes!.add(new FaultCodes.fromJson(v));
//       });
//     }
//     if (json['subTaskTypes'] != null) {
//       subTaskTypes = <SubTaskTypes>[];
//       json['subTaskTypes'].forEach((v) {
//         subTaskTypes!.add(new SubTaskTypes.fromJson(v));
//       });
//     }
//     if (json['subTaskStatuses'] != null) {
//       subTaskStatuses = <SubTaskStatuses>[];
//       json['subTaskStatuses'].forEach((v) {
//         subTaskStatuses!.add(new SubTaskStatuses.fromJson(v));
//       });
//     }
//     if (json['onHoldReasons'] != null) {
//       onHoldReasons = <OnHoldReasons>[];
//       json['onHoldReasons'].forEach((v) {
//         onHoldReasons!.add(new OnHoldReasons.fromJson(v));
//       });
//     }
//     if (json['countries'] != null) {
//       countries = <Countries>[];
//       json['countries'].forEach((v) {
//         countries!.add(new Countries.fromJson(v));
//       });
//     }
//     if (json['reporterTypes'] != null) {
//       reporterTypes = <ReporterTypes>[];
//       json['reporterTypes'].forEach((v) {
//         reporterTypes!.add(new ReporterTypes.fromJson(v));
//       });
//     }
//     if (json['reporterSubTypes'] != null) {
//       reporterSubTypes = <ReporterSubTypes>[];
//       json['reporterSubTypes'].forEach((v) {
//         reporterSubTypes!.add(new ReporterSubTypes.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     if (this.accounts != null) {
//       data['accounts'] = this.accounts!.map((v) => v.toJson()).toList();
//     }
//     if (this.projects != null) {
//       data['projects'] = this.projects!.map((v) => v.toJson()).toList();
//     }
//     if (this.buildings != null) {
//       data['buildings'] = this.buildings!.map((v) => v.toJson()).toList();
//     }
//     if (this.taskStatuses != null) {
//       data['taskStatuses'] = this.taskStatuses!.map((v) => v.toJson()).toList();
//     }
//     if (this.taskInstructions != null) {
//       data['taskInstructions'] =
//           this.taskInstructions!.map((v) => v.toJson()).toList();
//     }
//     if (this.types != null) {
//       data['types'] = this.types!.map((v) => v.toJson()).toList();
//     }
//     if (this.subTypes != null) {
//       data['subTypes'] = this.subTypes!.map((v) => v.toJson()).toList();
//     }
//     if (this.categories != null) {
//       data['categories'] = this.categories!.map((v) => v.toJson()).toList();
//     }
//     if (this.channels != null) {
//       data['channels'] = this.channels!.map((v) => v.toJson()).toList();
//     }
//     if (this.locs != null) {
//       data['locs'] = this.locs!.map((v) => v.toJson()).toList();
//     }
//     if (this.priorities != null) {
//       data['priorities'] = this.priorities!.map((v) => v.toJson()).toList();
//     }
//     if (this.faultCodes != null) {
//       data['faultCodes'] = this.faultCodes!.map((v) => v.toJson()).toList();
//     }
//     if (this.subTaskTypes != null) {
//       data['subTaskTypes'] = this.subTaskTypes!.map((v) => v.toJson()).toList();
//     }
//     if (this.subTaskStatuses != null) {
//       data['subTaskStatuses'] =
//           this.subTaskStatuses!.map((v) => v.toJson()).toList();
//     }
//     if (this.onHoldReasons != null) {
//       data['onHoldReasons'] =
//           this.onHoldReasons!.map((v) => v.toJson()).toList();
//     }
//     if (this.countries != null) {
//       data['countries'] = this.countries!.map((v) => v.toJson()).toList();
//     }
//     if (this.reporterTypes != null) {
//       data['reporterTypes'] =
//           this.reporterTypes!.map((v) => v.toJson()).toList();
//     }
//     if (this.reporterSubTypes != null) {
//       data['reporterSubTypes'] =
//           this.reporterSubTypes!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }
//
//
// class Categories {
//   int? id;
//   String? name;
//   String? code;
//
//   Categories({this.id, this.name, this.code});
//
//   Categories.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class ReporterTypes {
//   int? id;
//   String? name;
//   int? code;
//
//   ReporterTypes({this.id, this.name, this.code});
//
//   ReporterTypes.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class OnHoldReasons {
//   int? id;
//   String? name;
//   String? code;
//
//   OnHoldReasons({this.id, this.name, this.code});
//
//   OnHoldReasons.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
// class SubTaskStatuses {
//   int? id;
//   String? name;
//   int? code;
//
//   SubTaskStatuses({this.id, this.name, this.code});
//
//   SubTaskStatuses.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
// class FaultCodes {
//   int? id;
//   String? name;
//   String? code;
//
//   FaultCodes({this.id, this.name, this.code});
//
//   FaultCodes.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
//
// class Countries {
//   int? id;
//   String? name;
//   String? mobileCode;
//
//   Countries({this.id, this.name, this.mobileCode});
//
//   Countries.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     mobileCode = json['mobileCode'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['mobileCode'] = this.mobileCode;
//     return data;
//   }
// }
// class Priorities {
//   int? id;
//   String? name;
//   String? code;
//
//   Priorities({this.id, this.name, this.code});
//
//   Priorities.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class Locs {
//   int? id;
//   String? name;
//   String? code;
//
//   Locs({this.id, this.name, this.code});
//
//   Locs.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
// class Channels {
//   int? id;
//   String? name;
//   String? code;
//
//   Channels({this.id, this.name, this.code});
//
//   Channels.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
// class Types {
//   int? id;
//   String? name;
//   String? code;
//
//   Types({this.id, this.name, this.code});
//
//   Types.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
// class Accounts {
//   int? id;
//   String? name;
//   String? code;
//
//   Accounts({this.id, this.name, this.code});
//
//   Accounts.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class Buildings {
//   int? id;
//   String? name;
//   Null? code;
//   int? projectId;
//
//   Buildings({this.id, this.name, this.code, this.projectId});
//
//   Buildings.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//     projectId = json['projectId'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     data['projectId'] = this.projectId;
//     return data;
//   }
// }
//
// class TaskStatuses {
//   int? id;
//   String? name;
//   Null? code;
//
//   TaskStatuses({this.id, this.name, this.code});
//
//   TaskStatuses.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class TaskInstructions {
//   int? estimationMen;
//   int? estimatedLabourCost;
//   int? estimatedStockCost;
//   int? estimatedTimeInMins;
//   int? id;
//   String? name;
//   Null? code;
//
//   TaskInstructions(
//       {this.estimationMen,
//         this.estimatedLabourCost,
//         this.estimatedStockCost,
//         this.estimatedTimeInMins,
//         this.id,
//         this.name,
//         this.code});
//
//   TaskInstructions.fromJson(Map<String, dynamic> json) {
//     estimationMen = json['estimationMen'];
//     estimatedLabourCost = json['estimatedLabourCost'];
//     estimatedStockCost = json['estimatedStockCost'];
//     estimatedTimeInMins = json['estimatedTimeInMins'];
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['estimationMen'] = this.estimationMen;
//     data['estimatedLabourCost'] = this.estimatedLabourCost;
//     data['estimatedStockCost'] = this.estimatedStockCost;
//     data['estimatedTimeInMins'] = this.estimatedTimeInMins;
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class SubTypes {
//   int? typeId;
//   int? id;
//   String? name;
//   String? code;
//
//   SubTypes({this.typeId, this.id, this.name, this.code});
//
//   SubTypes.fromJson(Map<String, dynamic> json) {
//     typeId = json['typeId'];
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['typeId'] = this.typeId;
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class ReporterSubTypes {
//   int? id;
//   String? name;
//   int? reporterTypeId;
//   bool? isSelectable;
//
//   ReporterSubTypes(
//       {this.id, this.name, this.reporterTypeId, this.isSelectable});
//
//   ReporterSubTypes.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     reporterTypeId = json['reporterTypeId'];
//     isSelectable = json['isSelectable'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['reporterTypeId'] = this.reporterTypeId;
//     data['isSelectable'] = this.isSelectable;
//     return data;
//   }
// }
//
// class TaskLogInfo {
//   int? id;
//   String? title;
//   int? taskSlNo;
//   String? securityInfoId;
//   int? serviceTypeId;
//   String? dueDate;
//   int? reportedById;
//   String? reportedByName;
//   Null? userId;
//   String? reportedDate;
//   int? typeId;
//   int? subTypeId;
//   int? categoryId;
//   int? channelId;
//   Null? modeId;
//   int? locId;
//   String? locDate;
//   Null? summary;
//   int? priorityId;
//   Null? faultCodeId;
//   int? estimatedStockCost;
//   int? estimatedLabourCost;
//   int? estimatedTime;
//   int? projectId;
//   int? buildingId;
//   int? reporterTypeId;
//   int? reporterSubTypeId;
//   String? mobileCode;
//   String? mobileNo;
//   String? emailAddress;
//   int? statusId;
//   int? taskInstructionId;
//   Null? ratingId;
//   Null? completionDate;
//   Null? feedbackUserId;
//   Null? feedbackComments;
//   Null? feedbackDate;
//   Null? signatureUrl;
//   Null? onHoldReason;
//   Null? onHoldDate;
//   Null? onHoldReasonId;
//   Null? stPlannerId;
//   Null? stPlannerFreqId;
//   String? loggedByEmail;
//   String? loggedByDesignation;
//   List<Locations>? locations;
//
//   TaskLogInfo(
//       {this.id,
//         this.title,
//         this.taskSlNo,
//         this.securityInfoId,
//         this.serviceTypeId,
//         this.dueDate,
//         this.reportedById,
//         this.reportedByName,
//         this.userId,
//         this.reportedDate,
//         this.typeId,
//         this.subTypeId,
//         this.categoryId,
//         this.channelId,
//         this.modeId,
//         this.locId,
//         this.locDate,
//         this.summary,
//         this.priorityId,
//         this.faultCodeId,
//         this.estimatedStockCost,
//         this.estimatedLabourCost,
//         this.estimatedTime,
//         this.projectId,
//         this.buildingId,
//         this.reporterTypeId,
//         this.reporterSubTypeId,
//         this.mobileCode,
//         this.mobileNo,
//         this.emailAddress,
//         this.statusId,
//         this.taskInstructionId,
//         this.ratingId,
//         this.completionDate,
//         this.feedbackUserId,
//         this.feedbackComments,
//         this.feedbackDate,
//         this.signatureUrl,
//         this.onHoldReason,
//         this.onHoldDate,
//         this.onHoldReasonId,
//         this.stPlannerId,
//         this.stPlannerFreqId,
//         this.loggedByEmail,
//         this.loggedByDesignation,
//         this.locations});
//
//   TaskLogInfo.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     title = json['title'];
//     taskSlNo = json['taskSlNo'];
//     securityInfoId = json['securityInfoId'];
//     serviceTypeId = json['serviceTypeId'];
//     dueDate = json['dueDate'];
//     reportedById = json['reportedById'];
//     reportedByName = json['reportedByName'];
//     userId = json['userId'];
//     reportedDate = json['reportedDate'];
//     typeId = json['typeId'];
//     subTypeId = json['subTypeId'];
//     categoryId = json['categoryId'];
//     channelId = json['channelId'];
//     modeId = json['modeId'];
//     locId = json['locId'];
//     locDate = json['locDate'];
//     summary = json['summary'];
//     priorityId = json['priorityId'];
//     faultCodeId = json['faultCodeId'];
//     estimatedStockCost = json['estimatedStockCost'];
//     estimatedLabourCost = json['estimatedLabourCost'];
//     estimatedTime = json['estimatedTime'];
//     projectId = json['projectId'];
//     buildingId = json['buildingId'];
//     reporterTypeId = json['reporterTypeId'];
//     reporterSubTypeId = json['reporterSubTypeId'];
//     mobileCode = json['mobileCode'];
//     mobileNo = json['mobileNo'];
//     emailAddress = json['emailAddress'];
//     statusId = json['statusId'];
//     taskInstructionId = json['taskInstructionId'];
//     ratingId = json['ratingId'];
//     completionDate = json['completionDate'];
//     feedbackUserId = json['feedbackUserId'];
//     feedbackComments = json['feedbackComments'];
//     feedbackDate = json['feedbackDate'];
//     signatureUrl = json['signatureUrl'];
//     onHoldReason = json['onHoldReason'];
//     onHoldDate = json['onHoldDate'];
//     onHoldReasonId = json['onHoldReasonId'];
//     stPlannerId = json['stPlannerId'];
//     stPlannerFreqId = json['stPlannerFreqId'];
//     loggedByEmail = json['loggedByEmail'];
//     loggedByDesignation = json['loggedByDesignation'];
//     if (json['locations'] != null) {
//       locations = <Locations>[];
//       json['locations'].forEach((v) {
//         locations!.add(new Locations.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['title'] = this.title;
//     data['taskSlNo'] = this.taskSlNo;
//     data['securityInfoId'] = this.securityInfoId;
//     data['serviceTypeId'] = this.serviceTypeId;
//     data['dueDate'] = this.dueDate;
//     data['reportedById'] = this.reportedById;
//     data['reportedByName'] = this.reportedByName;
//     data['userId'] = this.userId;
//     data['reportedDate'] = this.reportedDate;
//     data['typeId'] = this.typeId;
//     data['subTypeId'] = this.subTypeId;
//     data['categoryId'] = this.categoryId;
//     data['channelId'] = this.channelId;
//     data['modeId'] = this.modeId;
//     data['locId'] = this.locId;
//     data['locDate'] = this.locDate;
//     data['summary'] = this.summary;
//     data['priorityId'] = this.priorityId;
//     data['faultCodeId'] = this.faultCodeId;
//     data['estimatedStockCost'] = this.estimatedStockCost;
//     data['estimatedLabourCost'] = this.estimatedLabourCost;
//     data['estimatedTime'] = this.estimatedTime;
//     data['projectId'] = this.projectId;
//     data['buildingId'] = this.buildingId;
//     data['reporterTypeId'] = this.reporterTypeId;
//     data['reporterSubTypeId'] = this.reporterSubTypeId;
//     data['mobileCode'] = this.mobileCode;
//     data['mobileNo'] = this.mobileNo;
//     data['emailAddress'] = this.emailAddress;
//     data['statusId'] = this.statusId;
//     data['taskInstructionId'] = this.taskInstructionId;
//     data['ratingId'] = this.ratingId;
//     data['completionDate'] = this.completionDate;
//     data['feedbackUserId'] = this.feedbackUserId;
//     data['feedbackComments'] = this.feedbackComments;
//     data['feedbackDate'] = this.feedbackDate;
//     data['signatureUrl'] = this.signatureUrl;
//     data['onHoldReason'] = this.onHoldReason;
//     data['onHoldDate'] = this.onHoldDate;
//     data['onHoldReasonId'] = this.onHoldReasonId;
//     data['stPlannerId'] = this.stPlannerId;
//     data['stPlannerFreqId'] = this.stPlannerFreqId;
//     data['loggedByEmail'] = this.loggedByEmail;
//     data['loggedByDesignation'] = this.loggedByDesignation;
//     if (this.locations != null) {
//       data['locations'] = this.locations!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }
//
// class Locations {
//   String? floorName;
//   String? unitName;
//   String? roomName;
//
//   Locations({this.floorName, this.unitName, this.roomName});
//
//   Locations.fromJson(Map<String, dynamic> json) {
//     floorName = json['floorName'];
//     unitName = json['unitName'];
//     roomName = json['roomName'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['floorName'] = this.floorName;
//     data['unitName'] = this.unitName;
//     data['roomName'] = this.roomName;
//     return data;
//   }
// }
//
// class Projects {
//   int? id;
//   String? name;
//   String? code;
//
//   Projects({this.id, this.name, this.code});
//
//   Projects.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
// class SubTaskTypes {
//   int? id;
//   String? name;
//   Null? code;
//
//   SubTaskTypes({this.id, this.name, this.code});
//
//   SubTaskTypes.fromJson(Map<String, dynamic> json) {
//     id = json['id'];
//     name = json['name'];
//     code = json['code'];
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['id'] = this.id;
//     data['name'] = this.name;
//     data['code'] = this.code;
//     return data;
//   }
// }
//
//
//
//
